# Generated by Django 3.0.5 on 2020-08-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=5000)),
                ('course', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
